-- Carga inicial de los 10 productos (copia de site/data/products.json). Aplicada el 28/09/2026.
-- Productos sin control de stock: stock 999 y show_stock=false (así create_order no los bloquea).
insert into public.products (id,name,brand,category,description,price,stock,show_stock,image,weight_kg) values
('procesador-intel-core-i5','Procesador Intel Core i5 13400 4.6GHz Turbo Socket 1700','Intel','Procesadores','10 núcleos (6 Performance + 4 Efficient) y 16 hilos para jugar, estudiar y trabajar con fluidez. Hasta 4,6 GHz en turbo, gráficos integrados UHD 730 y cooler incluido: listo para armar una PC equilibrada sin placa de video.',418500,999,false,'assets/img/products/producto-1.webp',1),
('procesador-intel-core-i7','Procesador Intel Core i7 13700 5.3GHz Turbo Socket 1700','Intel','Procesadores','16 núcleos y 24 hilos con arquitectura híbrida de Intel: los núcleos Performance se ocupan de los juegos y las tareas pesadas, y los Efficient del trabajo en segundo plano. Hasta 5,2 GHz, gráficos UHD 770 y compatible con DDR4 y DDR5.',662769,999,false,'assets/img/products/producto-2.webp',1),
('procesador-amd-ryzen-7','Procesador AMD Ryzen 7 5800X 4.7GHz Turbo AM4 - Sin Cooler','AMD','Procesadores','8 núcleos y 16 hilos Zen 3 con hasta 4,7 GHz: un clásico para gaming y creación de contenido en plataforma AM4. No trae cooler ni gráficos integrados: combinalo con un disipador y una placa de video.',309850,999,false,'assets/img/products/producto-3.webp',1),
('procesador-amd-ryzen-5','Procesador AMD Ryzen 5 8500G 5.0GHz Turbo AM5','AMD','Procesadores','6 núcleos y 12 hilos Zen 4 en 4 nm con gráficos AMD Radeon integrados: ideal para armar una PC gamer de entrada sin placa de video y actualizar después. Plataforma AM5 con DDR5 y cooler incluido.',359100,999,false,'assets/img/products/producto-4.webp',1),
('motherboard-asus-prime','Mother ASUS PRIME A620M-A - AM5 - CSM','ASUS','Motherboards','Motherboard Micro-ATX para Ryzen 7000/8000 (AM5) con chipset A620, DDR5, 2 ranuras M.2 y BIOS FlashBack para actualizar sin procesador. Salidas HDMI, DisplayPort y VGA para usar los gráficos integrados.',253000,999,false,'assets/img/products/producto-5.webp',1),
('placa-msi-geforce-gtx-ventus','Placa de Video MSI GeForce GTX 1650 4GB GDDR6 Ventus XS OC','MSI','Placas de video','Placa de video compacta de doble ventilador, pensada para jugar en 1080p en gabinetes chicos. Consume solo 75 W y no necesita cable de alimentación extra: funciona con fuentes desde 300 W.',305100,10,true,'assets/img/products/asus-gtx1660-01.webp',10),
('gabinete-antec-nx200m-white','Gabinete ANTEC NX200M WHITE','Antec','Gabinetes','Gabinete Micro-ATX blanco con panel lateral de vidrio templado, espacio para hasta 5 ventiladores y soporte para refrigeración líquida. Frente con USB 3.0 y 2 × USB 2.0.',63450,999,false,'assets/img/products/gabinete-antec-01.webp',1),
('fuente-aerocool-cylon-600w','Fuente Aerocool Cylon 600W Full Range RGB 80 Plus Bronze','Aerocool','Fuentes','Fuente ATX de 600 W con certificación 80 Plus Bronze, PFC activo y ventilador con iluminación RGB. Rango completo 100–240 V, 2 conectores PCIe y 5 SATA: suficiente para una PC gamer de gama media.',108000,999,false,'assets/img/products/fuente-aerocool-01.webp',1),
('memoria-tforce-delta-ddr4-8gb','Memoria Team DDR4 8GB 3600MHz T-Force Delta RGB Black CL18','Team Group','Memorias RAM','Módulo DDR4 de 8 GB a 3600 MHz CL18 con disipador negro e iluminación RGB de 120°. Ideal para sumar velocidad a Ryzen e Intel; combinalo con otro igual para tener Dual Channel.',52380,999,false,'assets/img/products/memoria-tforce-delta.webp',1),
('cooler-deepcool-ag400-plus','Cooler CPU DeepCool AG400 PLUS','DeepCool','Refrigeración','Disipador de torre con dos ventiladores de 120 mm y 4 heat pipes de contacto directo que disipa hasta 220 W. Silencioso gracias a los rodamientos hidráulicos y compatible con Intel LGA 1700/1200 y AMD AM5/AM4 sin tapar la memoria RAM.',51150,999,false,'assets/img/products/cooler-deepcool-02.webp',1)
on conflict (id) do nothing;
